package com.merryapps.tipcalculator.model.db;

import com.merryapps.tipcalculator.model.core.EntityState;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUOTES".
 */
public class QuoteEntity implements com.merryapps.tipcalculator.model.db.Entity {

    private Long id;
    /** Not-null value. */
    private String quote;
    /** Not-null value. */
    private String author;
    /** Not-null value. */
    private EntityState entityState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public QuoteEntity() {
    }

    public QuoteEntity(Long id) {
        this.id = id;
    }

    public QuoteEntity(Long id, String quote, String author, EntityState entityState) {
        this.id = id;
        this.quote = quote;
        this.author = author;
        this.entityState = entityState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getQuote() {
        return quote;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuote(String quote) {
        this.quote = quote;
    }

    /** Not-null value. */
    public String getAuthor() {
        return author;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthor(String author) {
        this.author = author;
    }

    /** Not-null value. */
    public EntityState getEntityState() {
        return entityState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntityState(EntityState entityState) {
        this.entityState = entityState;
    }

    // KEEP METHODS - put your custom methods here


    public QuoteEntity(String quote, String author, EntityState entityState) {
        this.quote = quote;
        this.author = author;
        this.entityState = entityState;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        QuoteEntity that = (QuoteEntity) o;

        return id != null ? id.equals(that.id) : that.id == null;

    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }


    // KEEP METHODS END

}
