package com.merryapps.easytip.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.merryapps.easytip.model.db.QuoteEntity;
import com.merryapps.easytip.model.db.UserSettingEntity;

import com.merryapps.easytip.model.db.QuoteEntityDao;
import com.merryapps.easytip.model.db.UserSettingEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig quoteEntityDaoConfig;
    private final DaoConfig userSettingEntityDaoConfig;

    private final QuoteEntityDao quoteEntityDao;
    private final UserSettingEntityDao userSettingEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        quoteEntityDaoConfig = daoConfigMap.get(QuoteEntityDao.class).clone();
        quoteEntityDaoConfig.initIdentityScope(type);

        userSettingEntityDaoConfig = daoConfigMap.get(UserSettingEntityDao.class).clone();
        userSettingEntityDaoConfig.initIdentityScope(type);

        quoteEntityDao = new QuoteEntityDao(quoteEntityDaoConfig, this);
        userSettingEntityDao = new UserSettingEntityDao(userSettingEntityDaoConfig, this);

        registerDao(QuoteEntity.class, quoteEntityDao);
        registerDao(UserSettingEntity.class, userSettingEntityDao);
    }
    
    public void clear() {
        quoteEntityDaoConfig.getIdentityScope().clear();
        userSettingEntityDaoConfig.getIdentityScope().clear();
    }

    public QuoteEntityDao getQuoteEntityDao() {
        return quoteEntityDao;
    }

    public UserSettingEntityDao getUserSettingEntityDao() {
        return userSettingEntityDao;
    }

}
