package com.merryapps.easytip.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.merryapps.easytip.model.framework.EntityStateConverter;
import com.merryapps.easytip.model.tip.UserSettingTypeConverter;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_SETTINGS".
*/
public class UserSettingEntityDao extends AbstractDao<UserSettingEntity, Long> {

    public static final String TABLENAME = "USER_SETTINGS";

    /**
     * Properties of entity UserSettingEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserSettingType = new Property(1, String.class, "userSettingType", false, "USER_SETTING_TYPE");
        public final static Property UserSettingValue = new Property(2, String.class, "userSettingValue", false, "USER_SETTING_VALUE");
        public final static Property EntityState = new Property(3, String.class, "entityState", false, "ENTITY_STATE");
    };

    private final UserSettingTypeConverter userSettingTypeConverter = new UserSettingTypeConverter();
    private final EntityStateConverter entityStateConverter = new EntityStateConverter();

    public UserSettingEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UserSettingEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_SETTINGS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_SETTING_TYPE\" TEXT NOT NULL UNIQUE ," + // 1: userSettingType
                "\"USER_SETTING_VALUE\" TEXT NOT NULL ," + // 2: userSettingValue
                "\"ENTITY_STATE\" TEXT NOT NULL );"); // 3: entityState
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_SETTINGS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserSettingEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, userSettingTypeConverter.convertToDatabaseValue(entity.getUserSettingType()));
        stmt.bindString(3, entity.getUserSettingValue());
        stmt.bindString(4, entityStateConverter.convertToDatabaseValue(entity.getEntityState()));
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserSettingEntity readEntity(Cursor cursor, int offset) {
        UserSettingEntity entity = new UserSettingEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            userSettingTypeConverter.convertToEntityProperty(cursor.getString(offset + 1)), // userSettingType
            cursor.getString(offset + 2), // userSettingValue
            entityStateConverter.convertToEntityProperty(cursor.getString(offset + 3)) // entityState
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserSettingEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserSettingType(userSettingTypeConverter.convertToEntityProperty(cursor.getString(offset + 1)));
        entity.setUserSettingValue(cursor.getString(offset + 2));
        entity.setEntityState(entityStateConverter.convertToEntityProperty(cursor.getString(offset + 3)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserSettingEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserSettingEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
